package org.javamisc.jee.entitycrud;

import java.lang.annotation.Target;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;



/**
 * Configure generation of CRUD views.
 */
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface CrudConfig
{
  /**
   * Control the order in which properties are displayed.
   *
   * <p>Properties are to be listed by name. The special wildcard
   * property {@code "*"} denotes all properties that are not
   * expressly mentioned. This must be the last array element.</p>
   *
   * <p>If this property is set to a non-null value, properties will
   * be listed in the order they occur in this array. Properties
   * occurring in the array but not found in the entity to be
   * displayed are ignored. Properties that are not listed in the
   * array are not displayed unless the wildcard property {@code "*"}
   * is used.</p>
   */
  String[] propertyOrder() default {"*"};

  /**
   * <strong>Currently ignored</strong> A format string to generate
   * URLs to a customised view for the entity.
   *
   * <p>This element enables replacing the views generated by the CRUD
   * system with customised views. The value of this element be a
   * format string containing exactly one {@code %s} conversion. The
   * expression {@code String.format(entityViewFormat(),
   * entityId.toString())} will be used to generate links to entities
   * of the annotated class.</p>
   *
   * <p>An empty string (the default value of this element) disables
   * this feature.</p>
   *
   * <p>This configuration takes precedence over the {@see
   * propertyOrder} element.</p>
   */
  String entityViewFormat() default "";
}
